#!/usr/bin/php
<?php
/**

    StatiCache 0.1

    Static Cached Content Creator
    Ryan Shaltry, http://ryanshaltry.com

    OVERVIEW
    Creates static HTML versions of CMS/dynamic content to alleviate
    application server workload.

    INSTALL
    1. Place the staticache PHP script into a directory in the $PATH
    2. Verify staticache script is executable (755)
    3. Verify the location of the PHP interpreter on line 1 of script

    USAGE
    $ staticache COMMAND

    The staticache command can be run from any directory, and reads the
    configuration located at ~/.staticache by default.  The -f option
    can [optionally] be specified to point the script to config file.

    NOTE: Run staticache with no options to view usage information.

    BASIC EXAMPLES
    $ staticache enable
    $ staticache disable
    $ staticache status
    $ staticache refresh

    PREFERENCES
    The staticache configuration file has the following syntax:

    [config]
    static-dir = /path/to/public/static
    colors = 1
    debug = 0
    timeout = 10
    retries = 3
    username = basic_user
    password = basic_pass

    [urls]
    url[] = http://local.domain.com/
    url[] = http://local.domain.com/shop/
    url[] = http://local.domain.com/shop/accessories.html

    EXAMPLE APACHE CONFIGURATION
    The following type of configuration will need to be added to your Apache
    VirtualHosts(s) in order to use StatiCache capabilities.

    # StatiCache rewrites for file requests
    RewriteEngine On
    RewriteCond %{THE_REQUEST} GET
    RewriteCond %{DOCUMENT_ROOT}/static/$0 -f
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{QUERY_STRING} !(.+)
    RewriteRule ^(.+\.html)$ /static/$0 [L,QSA]

    # StatiCache rewrites for directory requests
    RewriteCond %{THE_REQUEST} GET
    RewriteCond %{DOCUMENT_ROOT}/static/$0/index.html -f
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{DOCUMENT_ROOT}/static/$0 -d
    RewriteCond %{QUERY_STRING} !(.+)
    RewriteRule ^(.*)$ /static/$0/index.html [L,QSA]

    LICENSE
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

error_reporting(E_ALL & ~E_NOTICE);
ini_set('display_errors', 'On');

class Cfg_Default {

    const DEBUG  = 0;
    const COLORS = 1;
    const TIMEOUT = 10;
    const RETRIES = 3;

}

class CacheDir {

    static function create($url) {
        $_sub = dirname(parse_url(CacheUrl::dirIndex($url), PHP_URL_PATH));
        $_dir = sprintf('%s%s', Cfg::get('static-dir'), $_sub);
        if(!is_dir($_dir)) {
            mkdir($_dir, 0755, TRUE);
            Shell::output(sprintf('Created new static subdirectory: %s', $_dir), 'debug');
        }
    }

}

class CacheUrl {

    static function write($url) {
        $_timeout = (Cfg::get('timeout') > -1) ? Cfg::get('timeout') : 10;
        $_limit = (Cfg::get('retries') > 0) ? Cfg::get('retries') : 1;
        $_url = (file_exists(CacheUrl::urlToFile($url))) ? $url.'?1' : $url;
        $_msg_fail = 'Request for %s #%d failed, waiting %ds to retry...';

        Shell::output(sprintf('Requesting content for %s...', $url));

        for($i=1;$i<=$_limit;$i++) {
            $ch = curl_init($_url);

            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $_timeout);
            curl_setopt($ch, CURLOPT_NOSIGNAL, TRUE);

            $_user = Cfg::get('username');
            $_pass = Cfg::get('password');
            if(Cfg::get('username') && Cfg::get('password')) {
                $_userpass = sprintf('%s:%s', Cfg::get('username'), Cfg::get('password'));
                curl_setopt($ch, CURLOPT_USERPWD, $_userpass);
                curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
            }

            $_data   = curl_exec($ch);
            $_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            Shell::output(sprintf('HTTP Response: %s', $_status), 'debug');
            curl_close($ch);

            if (!strlen(trim($_data))) {
                throw new Exception('No data');
            }
            if($_status != '200') {
                if($i == $_limit) {
                    throw new Exception(sprintf('Status %s, %d attempts', $_status, $_limit));
                }
                else {
                    Shell::output(sprintf($_msg_fail, $url, $i, $_timeout), 'error');
                    sleep($_timeout);
                }
            }
            else {
                break;
            }
       }

        $_contents = sprintf("%s\n<!-- StatiCache: %s -->\n", $_data, @date("YmdHi"));
        $_filename = self::urlToFile($url);

        CacheDir::create($url);

        file_put_contents($_filename, $_contents);

        Shell::output(sprintf('Created cache file: %s', $_filename), 'debug');
        Shell::output(sprintf('Successfully wrote cache for %s', $url), 'success');
    }

    static function purge($url) {
        $_filename = sprintf('%s%s', cfg::get('static-dir'), parse_url($url, PHP_URL_PATH));
        if(is_file($_filename)) {
            unlink($_filename);
            Shell::output(sprintf('Removed cache for %s...', $url), 'success');
        }
        if(is_dir($_filename)) {
            $_filename .= DIRECTORY_SEPARATOR . 'index.html';
            if(is_file($_filename)) {
                unlink($_filename);
                Shell::output(sprintf('Removed cache for %s...', $url), 'success');
            }
        }
    }

    static function urlToFile($url) {
        $_sub = self::dirIndex(preg_replace('/.+\/\/.+?\//', '/', $url));
        return sprintf('%s%s', Cfg::get('static-dir'), $_sub);
    }

    static function dirIndex($url) {
        $url .= (preg_match('/.*\/$/', trim($url))) ? 'index.html' : null;
        return $url;
    }

}

class Command_Enable extends Command_Abstract {

    var $usage = "- Enable StatiCache\n";

    public function execute($args=array()) {
        Command_Refresh::execute();
    }

}

class Command_Disable extends Command_Abstract {
    var $usage = "- Disable StatiCache\n";

    public function execute($args=array()) {
        $_urls = Cfg::urls();
        Shell::output(sprintf('Disabling %d StatiCache content cache(s)...', count($_urls)));

        foreach($_urls as $_url) {
            CacheUrl::purge($_url);
        }
    }
}

class Command_Refresh extends Command_Abstract {
    var $usage = "- Refresh StatiCache caches\n";

    static function execute($args=array()) {
        $_urls = Cfg::urls();
        Shell::output(sprintf('Refreshing %d StatiCache content cache(s)...', count($_urls)));

        foreach($_urls as $_url) {
            try {
                CacheUrl::write($_url);
            }
            catch(Exception $e) {
                Shell::output(sprintf('Unable to create content cache for %s (%s)', $_url, $e->getMessage()), 'error');
            }
        }
    }

}

class Command_Status extends Command_Abstract {
    var $usage = "- Show StatiCache status information\n";

    static function execute($args=array()) {
        foreach(Cfg::urls() as $_url) {
            $_file = CacheUrl::urlToFile($_url);
            $_filename = str_replace(Cfg::get('static-dir'), null, $_file);
            Shell::output(sprintf('URL: %s', $_url));
            if(file_exists($_file)) {
                $_age = (int) time()-filemtime($_file);
                $_size = (int) filesize($_file);
                Shell::output(sprintf('- Cache file found: %s (%ss old, %d bytes)', $_filename, $_age, $_size), 'success');

                if(preg_match('/title>(.*)<\/title/', file_get_contents($_file), $_title)) {
                    Shell::output(sprintf('- Cache page title: %s', $_title[1]), 'success');
                }
            } else {
                Shell::output('- Cache file not found.', 'error');
            }
        }
    }

}

class Command_Abstract {

    public function usage() {
        return ($this->usage) ? $this->usage : 'Command usage information not available.';
    }

}

class Cfg {

    static protected $_settings;
    static protected $_urls;

    static function get($setting) {
        return (isset(self::$_settings[$setting])) ? self::$_settings[$setting] : NULL;
    }

    static function set($setting, $value) {
        self::$_settings = (is_array(self::$_settings)) ? self::$_settings : array();
        self::$_settings[$setting] = $value;
    }

    static function url($url) {
        self::$_urls = (is_array(self::$_urls)) ? self::$_urls : array();
        self::$_urls[] = $url;
    }

    static function urls() {
        return (is_array(self::$_urls)) ? self::$_urls : array();
    }

    static function ini($args) {
        $_ds = DIRECTORY_SEPARATOR;
        $_cfgPtr = array_search('-f', $args);
        if($_cfgPtr && $args[($_cfgPtr+1)]) {
            $_cfgFile = $args[($_cfgPtr+1)];
        } else {
            $_cfgFile = $_SERVER['HOME'].$_ds.'.staticache';
        }
        if(file_exists($_cfgFile)) {
            $_cfg = parse_ini_file($_cfgFile, TRUE);
            foreach($_cfg['config'] as $_key => $_val) {
                self::set($_key, $_val);
            }
            foreach($_cfg['urls']['url'] as $_url) {
                self::url($_url);
            }
        }
        else {
            throw new Exception(sprintf('Unable to load configuration file (%s)', $_cfgFile));
        }
        return self::$_settings;
    }

}

class Color {
    const RESET        = "\033[0m";
    const BLACK        = "\033[0;30m";
    const RED          = "\033[0;31m";
    const GREEN        = "\033[0;32m";
    const BROWN        = "\033[0;33m";
    const BLUE         = "\033[0;34m";
    const PURPLE       = "\033[0;35m";
    const CYAN         = "\033[0;36m";
    const LIGHT_GRAY   = "\033[0;37m";
    const GRAY         = "\033[1;30m";
    const LIGHT_RED    = "\033[1;31m";
    const LIGHT_GREEN  = "\033[1;32m";
    const YELLOW       = "\033[1;33m";
    const LIGHT_BLUE   = "\033[1;34m";
    const LIGHT_PURPLE = "\033[1;35m";
    const LIGHT_CYAN   = "\033[1;36m";
    const WHITE        = "\033[1;37m";

    static function output($str=null, $color='white') {
        $color = strtoupper($color);
        return (constant("Color::$color")) ? constant("Color::$color") . $str . constant("Color::RESET") : $str;
    }
}

class Shell {

    protected $script;
    protected $command;
    protected $args;

    protected $_version = '0.1';

    var $commands = array('enable', 'disable', 'refresh', 'status');

    var $usage = "\nUSAGE:   staticache COMMAND\nEXAMPLE: staticache refresh\n";

    public function run($args) {
        $ini = Cfg::ini($args);

        $this->script  = array_shift($args);
        $this->command = array_shift($args);
        $this->args    = $args;

        $_debug = (isset($ini['debug'])) ? $ini['debug'] : Cfg_Default::DEBUG;
        $_colors = (isset($ini['colors'])) ? $ini['colors'] : Cfg_Default::COLORS;

        Cfg::set('debug', $_debug);
        Cfg::set('colors', $_colors);

        $this->welcome();

        $_commandClass = 'Command_' . ucwords($this->command);

        if($this->command && class_exists($_commandClass)) {
            $_commandObj = new $_commandClass;
            echo $_commandObj->execute($this->args);
        }
        else {
            Shell::output($this->usage, 'warning');
            foreach($this->commands as $_command) {
                Shell::output($_command.':', 'warning');
                $_commandClass = 'Command_' . ucwords($_command);
                $_commandClassObj = new $_commandClass;
                Shell::output($_commandClassObj->usage(), 'default');
            }
        }
    }

    static function output($str=null, $type='default') {
        $colors = array('default' => 'white',
                        'success' => 'green',
                        'error'   => 'red',
                        'warning' => 'yellow',
                        'debug' => 'gray');

        if($type != 'debug' || Cfg::get('debug')) {
            $color = ($colors[$type]) ? $colors[$type] : $colors['default'];
            $str  .= "\n";
            echo (Cfg::get('colors')) ? Color::output($str, $color) : $str;
        }
    }

    protected function welcome() {
        Shell::output(sprintf('Welcome to StatiCache v%s', $this->_version), 'success');
        Shell::output(sprintf('StatiCache Directory: %s', Cfg::get('static-dir')), 'debug');
    }

    public function exception($exception, $e = null) {
        Shell::output($exception, 'error');
        if ($e && Cfg::get('debug')) {
            var_dump($e);
        }
        exit;
    }

}

$shell = new Shell;
$shell->run($argv);
